/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc.builder;

import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Jamila
 */
public class BuildYourPCWindow extends javax.swing.JFrame {

    private int clicked;
    /**
     * Creates new form BuildYourPCWindow
     */
    public BuildYourPCWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        videoCard = new javax.swing.JButton();
        Case = new javax.swing.JButton();
        hardDrive = new javax.swing.JButton();
        motheBoard = new javax.swing.JButton();
        cPU = new javax.swing.JButton();
        memory = new javax.swing.JButton();
        oS = new javax.swing.JButton();
        heatSink = new javax.swing.JButton();
        powerSupply = new javax.swing.JButton();
        partSelector = new javax.swing.JInternalFrame();
        shoppingCart = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        videoCard.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        videoCard.setText("Video Card");
        videoCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoCardActionPerformed(evt);
            }
        });

        Case.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        Case.setText("Case");
        Case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseActionPerformed(evt);
            }
        });

        hardDrive.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        hardDrive.setText("Hard Drive");
        hardDrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardDriveActionPerformed(evt);
            }
        });

        motheBoard.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        motheBoard.setText("MotherBoard");
        motheBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motheBoardActionPerformed(evt);
            }
        });

        cPU.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        cPU.setText("CPU");
        cPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPUActionPerformed(evt);
            }
        });

        memory.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        memory.setText("Memory");
        memory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryActionPerformed(evt);
            }
        });

        oS.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        oS.setText("Operating System");
        oS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSActionPerformed(evt);
            }
        });

        heatSink.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        heatSink.setText("Heat Sink");
        heatSink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatSinkActionPerformed(evt);
            }
        });

        powerSupply.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        powerSupply.setText("Power Supply");
        powerSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerSupplyActionPerformed(evt);
            }
        });

        partSelector.setVisible(true);

        javax.swing.GroupLayout partSelectorLayout = new javax.swing.GroupLayout(partSelector.getContentPane());
        partSelector.getContentPane().setLayout(partSelectorLayout);
        partSelectorLayout.setHorizontalGroup(
            partSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        partSelectorLayout.setVerticalGroup(
            partSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        shoppingCart.setVisible(true);

        javax.swing.GroupLayout shoppingCartLayout = new javax.swing.GroupLayout(shoppingCart.getContentPane());
        shoppingCart.getContentPane().setLayout(shoppingCartLayout);
        shoppingCartLayout.setHorizontalGroup(
            shoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        shoppingCartLayout.setVerticalGroup(
            shoppingCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );

        desktopPane.setLayer(videoCard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(Case, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(hardDrive, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(motheBoard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(cPU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(memory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(oS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(heatSink, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(powerSupply, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(partSelector, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(shoppingCart, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(cPU, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(motheBoard))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(powerSupply)
                                .addGap(74, 74, 74)
                                .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(videoCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hardDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Case))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addComponent(heatSink)
                        .addGap(61, 61, 61)
                        .addComponent(oS))
                    .addComponent(partSelector))
                .addGap(57, 57, 57)
                .addComponent(shoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motheBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoCard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hardDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Case, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heatSink, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shoppingCart)
                    .addComponent(partSelector))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPUActionPerformed
       System.out.println("CPU button was pressed.");
//       for(partSelector.action(evt, evt)){
//           
//       }
       
       

    }//GEN-LAST:event_cPUActionPerformed

    private void hardDriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardDriveActionPerformed
        System.out.println("Hard Drive button was pressed.");
    }//GEN-LAST:event_hardDriveActionPerformed

    private void motheBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motheBoardActionPerformed
        System.out.println("Motherboard button was pressed.");
    }//GEN-LAST:event_motheBoardActionPerformed

    private void videoCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoCardActionPerformed
        System.out.println("Video Card button was pressed.");
        
//        FileReader videoCards =  new FileReader("NvidiaVideoCards.txt");
//        BufferedReader input = new BufferedReader(videoCards);

       
    }//GEN-LAST:event_videoCardActionPerformed

    private void memoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryActionPerformed
        System.out.println("Memory button was pressed.");
    }//GEN-LAST:event_memoryActionPerformed

    private void oSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSActionPerformed
       System.out.println("Operating system button was pressed.");
    }//GEN-LAST:event_oSActionPerformed

    private void powerSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerSupplyActionPerformed
        System.out.println("Power Supply button was pressed.");
    }//GEN-LAST:event_powerSupplyActionPerformed

    private void CaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseActionPerformed
        System.out.println("Case button was pressed");
    }//GEN-LAST:event_CaseActionPerformed

    private void heatSinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatSinkActionPerformed
        System.out.println("Heat sink button was pressed.");
    }//GEN-LAST:event_heatSinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildYourPCWindow().setVisible(true);
                new BuildYourPCWindow().setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
        
    }
    
//    public void actionPerformed(JButton cPU){
// 
//   }
    
    public void actionPerformed(ActionEvent cPU){
        clicked++;
    }
    
    
    
    
//    public static void textFileReader(){
//        BufferedReader input = new BufferedReader(new FileReader("NvidiaVideoCards.txt"));
//        try {
//            StringBuilder sb = new StringBuilder();
//            String line = input.readLine();
//
//            while (line != null) {
//                sb.append(line);
//                line = input.readLine();
//            }
//            String everything = sb.toString();
//        } finally {
//            .close();
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Case;
    private javax.swing.JButton cPU;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton hardDrive;
    private javax.swing.JButton heatSink;
    private javax.swing.JButton memory;
    private javax.swing.JButton motheBoard;
    private javax.swing.JButton oS;
    private javax.swing.JInternalFrame partSelector;
    private javax.swing.JButton powerSupply;
    private javax.swing.JInternalFrame shoppingCart;
    private javax.swing.JButton videoCard;
    // End of variables declaration//GEN-END:variables
}
