/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc.builder;

import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Jamila
 */
public class BuildYourPCWindow extends javax.swing.JFrame {

    private int clicked;
    /**
     * Creates new form BuildYourPCWindow
     */
    public BuildYourPCWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        partSelector = new javax.swing.JInternalFrame();
        hardDrive = new javax.swing.JButton();
        motheBoard = new javax.swing.JButton();
        cPU = new javax.swing.JButton();
        memory = new javax.swing.JButton();
        oS = new javax.swing.JButton();
        heatSink = new javax.swing.JButton();
        powerSupply = new javax.swing.JButton();
        videoCard = new javax.swing.JButton();
        Case = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        partSelector.setVisible(true);
        partSelector.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                partSelectorInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout partSelectorLayout = new javax.swing.GroupLayout(partSelector.getContentPane());
        partSelector.getContentPane().setLayout(partSelectorLayout);
        partSelectorLayout.setHorizontalGroup(
            partSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        partSelectorLayout.setVerticalGroup(
            partSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );

        hardDrive.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        hardDrive.setText("Hard Drive");
        hardDrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardDriveActionPerformed(evt);
            }
        });

        motheBoard.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        motheBoard.setText("MotherBoard");
        motheBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motheBoardActionPerformed(evt);
            }
        });

        cPU.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        cPU.setText("CPU");
        cPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPUActionPerformed(evt);
            }
        });

        memory.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        memory.setText("Memory");
        memory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryActionPerformed(evt);
            }
        });

        oS.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        oS.setText("Operating System");
        oS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oSActionPerformed(evt);
            }
        });

        heatSink.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        heatSink.setText("Heat Sink");
        heatSink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heatSinkActionPerformed(evt);
            }
        });

        powerSupply.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        powerSupply.setText("Power Supply");
        powerSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerSupplyActionPerformed(evt);
            }
        });

        videoCard.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        videoCard.setText("Video Card");
        videoCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoCardActionPerformed(evt);
            }
        });

        Case.setFont(new java.awt.Font("Gadugi", 1, 21)); // NOI18N
        Case.setText("Case");
        Case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseActionPerformed(evt);
            }
        });

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cPU, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(motheBoard)
                                .addGap(18, 18, 18)
                                .addComponent(videoCard)
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(powerSupply)
                                .addGap(18, 18, 18)
                                .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heatSink)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hardDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Case))
                            .addComponent(oS)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(partSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPU, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(motheBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoCard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hardDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Case, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(powerSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memory, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heatSink, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oS, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPUActionPerformed
       System.out.println("CPU button was pressed.");
    }//GEN-LAST:event_cPUActionPerformed

    private void partSelectorInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_partSelectorInternalFrameActivated
        System.out.println("Activated.");
    }//GEN-LAST:event_partSelectorInternalFrameActivated

    private void hardDriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardDriveActionPerformed
        System.out.println("Hard Drive button was pressed.");
    }//GEN-LAST:event_hardDriveActionPerformed

    private void motheBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motheBoardActionPerformed
        System.out.println("Motherboard button was pressed.");
    }//GEN-LAST:event_motheBoardActionPerformed

    private void videoCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoCardActionPerformed
        System.out.println("Video Card button was pressed.");
    }//GEN-LAST:event_videoCardActionPerformed

    private void memoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryActionPerformed
        System.out.println("Memory button was pressed.");
    }//GEN-LAST:event_memoryActionPerformed

    private void oSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oSActionPerformed
       System.out.println("Operating system button was pressed.");
    }//GEN-LAST:event_oSActionPerformed

    private void powerSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerSupplyActionPerformed
        System.out.println("Power Supply button was pressed.");
    }//GEN-LAST:event_powerSupplyActionPerformed

    private void CaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseActionPerformed
        System.out.println("Case button was pressed");
    }//GEN-LAST:event_CaseActionPerformed

    private void heatSinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heatSinkActionPerformed
        System.out.println("Heat sink button was pressed.");
    }//GEN-LAST:event_heatSinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildYourPCWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildYourPCWindow().setVisible(true);
                new BuildYourPCWindow().setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }
    
    public void actionPerformed(JButton cPU){
         boolean isValid = true;    
        JInternalFrame partSelector = new JInternalFrame();
        
        partSelector.setResizable(isValid);
        partSelector.setClosable(!isValid);
        partSelector.setVisible(isValid);
        
        cPU = new JButton ("Clicked: "+clicked+" Times!");
        partSelector.add(cPU);
    }
    
    public void actionPerformed(ActionEvent cPU){
        clicked++;
    }
    
    
//    public static void textFileReader(){
//        BufferedReader input = new BufferedReader(new FileReader("NvidiaVideoCards.txt"));
//        try {
//            StringBuilder sb = new StringBuilder();
//            String line = input.readLine();
//
//            while (line != null) {
//                sb.append(line);
//                line = input.readLine();
//            }
//            String everything = sb.toString();
//        } finally {
//            .close();
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Case;
    private javax.swing.JButton cPU;
    private javax.swing.JButton hardDrive;
    private javax.swing.JButton heatSink;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JButton memory;
    private javax.swing.JButton motheBoard;
    private javax.swing.JButton oS;
    private javax.swing.JInternalFrame partSelector;
    private javax.swing.JButton powerSupply;
    private javax.swing.JButton videoCard;
    // End of variables declaration//GEN-END:variables
}
